basic:
    name: SEOD-653
    environments:
        production: 'https://thisoldhouse.jppadmin.com/'
        staging: 'https://staging.thisoldhouse.jppadmin.com/'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - 'worst-home-warranty-companies-2?src=jpplatform'
        - 'solar-companies-illinois-2?src=jpplatform'
        - 'home-warranty-new-jersey-2?src=jpplatform'
        - '?src=jpplatform'
        - 'best-gutter-guards-for-pine-needles?src=jpplatform'
        - 'best-pest-control-companies?src=jpplatform'
        - 'solar-companies-arizona?src=jpplatform'
        - 'best-solar-panels-for-homes?src=jpplatform'
        - 'solar-companies-massachusetts?src=jpplatform'
        - 'solar-companies-florida?src=jpplatform'
        - 'allied-home-warranty?src=jpplatform'
        - '365-home-warranty?src=jpplatform'
        - 'pool-warranty?src=jpplatform'
        - 'cheapest-home-warranty?src=jpplatform'
        - 'best-home-warranty-for-hvac?src=jpplatform'
        - 'worst-home-warranty-companies?src=jpplatform'
        - 'best-refrigerator-warranty?src=jpplatform'
        - 'well-warranty?src=jpplatform'
        - 'home-warranty-for-rental-property?src=jpplatform'
        - 'mobile-home-warranty?src=jpplatform'
        - 'home-warranty-furnace?src=jpplatform'
        - 'home-warranty-utah?src=jpplatform'
        - 'home-warranty-delaware?src=jpplatform'
        - 'home-warranty-new-mexico?src=jpplatform'
        - 'home-warranty-alabama?src=jpplatform'
        - 'home-warranty-rhode-island?src=jpplatform'
        - 'home-warranty-west-virginia?src=jpplatform'
        - 'home-warranty-idaho?src=jpplatform'
        - 'home-warranty-kansas?src=jpplatform'
        - 'home-warranty-kentucky?src=jpplatform'
        - 'home-warranty-mississippi?src=jpplatform'
        - 'home-warranty-maine?src=jpplatform'
        - 'home-warranty-nebraska?src=jpplatform'
        - 'home-warranty-south-dakota?src=jpplatform'
        - 'home-warranty-montana?src=jpplatform'
        - 'home-warranty-alaska?src=jpplatform'
        - 'home-warranty-wyoming?src=jpplatform'
        - 'home-warranty-north-dakota?src=jpplatform'
        - 'home-warranty-vermont?src=jpplatform'
        - 'home-warranty-new-hampshire?src=jpplatform'
        - 'home-warranty-for-veterans?src=jpplatform'
        - 'home-warranty-for-condo?src=jpplatform'
        - 'usaa-home-warranty?src=jpplatform'
        - 'home-warranty-plumbing?src=jpplatform'
        - 'best-home-warranty-for-high-end-appliances?src=jpplatform'
        - 'globe-home-protection?src=jpplatform'
        - 'freedom-home-warranty?src=jpplatform'
        - 'home-warranty-louisiana?src=jpplatform'
        - 'home-warranty-illinois?src=jpplatform'
        - 'home-warranty-tennessee?src=jpplatform'
        - 'home-warranty-indiana?src=jpplatform'
        - 'home-warranty-oregon?src=jpplatform'
        - 'home-warranty-arkansas?src=jpplatform'
        - 'home-warranty-massachusetts?src=jpplatform'
        - 'home-warranty-colorado?src=jpplatform'
        - 'cheap-solar-panels?src=jpplatform'
        - 'best-solar-companies-north-carolina?src=jpplatform'
        - 'best-solar-companies-colorado?src=jpplatform'
        - 'best-solar-companies-texas?src=jpplatform'
        - 'moving-companies-for-small-moves?src=jpplatform'
        - 'moving-companies-hawaii?src=jpplatform'
        - 'moving-companies-indiana?src=jpplatform'
        - 'moving-companies-for-military-members?src=jpplatform'
        - 'moving-companies-maine?src=jpplatform'
        - 'moving-companies-michigan?src=jpplatform'
        - 'moving-companies-maryland?src=jpplatform'
        - 'moving-companies-massachusetts?src=jpplatform'
        - 'moving-companies-north-carolina?src=jpplatform'
        - 'moving-companies-ohio?src=jpplatform'
        - 'moving-companies-utah?src=jpplatform'
        - 'moving-companies-south-carolina?src=jpplatform'
        - 'moving-companies-california?src=jpplatform'
        - 'moving-companies-georgia?src=jpplatform'
        - 'moving-companies-kentucky?src=jpplatform'
        - 'moving-companies-tennessee?src=jpplatform'
        - 'moving-companies-minnesota?src=jpplatform'
        - 'moving-companies-wisconsin?src=jpplatform'
        - 'moving-companies-virginia?src=jpplatform'
        - 'moving-companies-oregon?src=jpplatform'
        - 'moving-companies-illinois?src=jpplatform'
        - 'moving-companies-alabama?src=jpplatform'
        - 'moving-companies-colorado?src=jpplatform'
        - 'moving-companies-pennsylvania?src=jpplatform'
        - 'moving-companies-nevada?src=jpplatform'
        - 'moving-companies-florida?src=jpplatform'
        - 'pet-shipping-companies?src=jpplatform'
        - 'best-moving-companies-for-apartments?src=jpplatform'
        - 'moving-from-new-york-to-california?src=jpplatform'
        - 'moving-companies-louisiana?src=jpplatform'
        - 'best-packing-and-moving-companies?src=jpplatform'
        - 'cheapest-moving-containers?src=jpplatform'
        - 'moving-companies-washington?src=jpplatform'
        - 'best-moving-companies-for-seniors?src=jpplatform'
        - 'moving-companies-new-jersey?src=jpplatform'
        - 'moving-companies-rhode-island?src=jpplatform'
        - 'cheapest-moving-truck-rental?src=jpplatform'
        - 'best-moving-container-companies?src=jpplatform'
        - 'best-moving-companies-for-antiques?src=jpplatform'
        - 'moving-companies-delaware?src=jpplatform'
        - 'moving-from-california-to-florida?src=jpplatform'
        - 'moving-companies-arizona?src=jpplatform'
        - 'cheap-moving-companies?src=jpplatform'
        - 'best-moving-companies?src=jpplatform'
        - 'best-pet-insurance?src=jpplatform'
        - 'solar-panel-cost-florida?src=jpplatform'
        - 'moving-companies-new-york?src=jpplatform'
        - 'best-lawn-care-services?src=jpplatform'
        - 'most-efficient-solar-panels?src=jpplatform'
        - 'solar-companies-new-york?src=jpplatform'
        - 'best-solar-companies-new-mexico?src=jpplatform'
        - 'best-solar-batteries?src=jpplatform'
        - 'solar-panel-cost-new-jersey?src=jpplatform'
        - 'best-replacement-windows?src=jpplatform'
        - 'solar-companies-pennsylvania?src=jpplatform'
        - 'best-window-brands?src=jpplatform'
        - 'cheap-window-replacement?src=jpplatform'
        - 'moving-companies-iowa?src=jpplatform'
        - 'moving-companies-arkansas?src=jpplatform'
        - 'best-office-moving-companies?src=jpplatform'
        - 'best-piano-movers?src=jpplatform'
        - 'solar-companies-south-carolina?src=jpplatform'
        - 'moving-companies-mississippi?src=jpplatform'
        - 'moving-companies-vermont?src=jpplatform'
        - 'moving-companies-south-dakota?src=jpplatform'
        - 'best-flat-fee-movers?src=jpplatform'
        - 'moving-companies-alaska?src=jpplatform'
        - 'moving-companies-north-dakota?src=jpplatform'
        - 'moving-companies-nebraska?src=jpplatform'
        - 'solar-companies-georgia?src=jpplatform'
        - 'moving-companies-kansas?src=jpplatform'
        - 'moving-companies-montana?src=jpplatform'
        - 'moving-companies-new-mexico?src=jpplatform'
        - 'best-storm-windows?src=jpplatform'
        - 'best-window-installation-companies?src=jpplatform'
        - 'moving-companies-west-virginia?src=jpplatform'
        - 'moving-companies-new-hampshire?src=jpplatform'
        - 'moving-companies-idaho?src=jpplatform'
        - 'best-international-moving-companies?src=jpplatform'
        - 'short-distance-moving-companies?src=jpplatform'
        - 'moving-companies-oklahoma?src=jpplatform'
        - 'solar-companies-maryland?src=jpplatform'
        - 'arched-window-replacement?src=jpplatform'
        - 'moving-companies-missouri?src=jpplatform'
        - 'best-air-conditioner-brands?src=jpplatform'
        - 'solar-panel-cost-arizona?src=jpplatform'
        - 'pet-wellness-plans?src=jpplatform'
        - 'moving-companies-wyoming?src=jpplatform'
        - 'best-last-minute-movers?src=jpplatform'
        - 'solar-companies-utah?src=jpplatform'
        - 'sewer-line-warranty?src=jpplatform'
        - 'trane-ac-unit?src=jpplatform'
        - 'best-gutter-guards-for-metal-roofs?src=jpplatform'
        - 'solar-companies-connecticut?src=jpplatform'
        - 'best-flexible-solar-panels?src=jpplatform'
        - 'best-laminate-flooring?src=jpplatform'
        - 'best-walk-in-tubs?src=jpplatform'
        - 'best-long-distance-moving-companies?src=jpplatform'
        - 'amazon-home-warranty?src=jpplatform'
        - 'home-appliance-insurance?src=jpplatform'
        - 'best-furnace-brands?src=jpplatform'
        - 'wall-mounted-air-conditioner?src=jpplatform'
        - 'best-luxury-moving-companies?src=jpplatform'
        - 'best-solar-companies-virginia?src=jpplatform'
        - 'best-vinyl-windows?src=jpplatform'
        - 'best-solar-companes-minnesota?src=jpplatform'
        - 'best-solar-companies-hawaii?src=jpplatform'
        - 'best-solar-companies-nevada?src=jpplatform'
        - 'best-solar-companies-oregon?src=jpplatform'
        - 'best-solar-companies-ohio?src=jpplatform'
        - 'best-solar-companies-arkansas?src=jpplatform'
        - 'best-solar-companies-iowa?src=jpplatform'
        - 'best-solar-companies-new-hampshire?src=jpplatform'
        - 'best-solar-companies-missouri?src=jpplatform'
        - 'best-solar-companies-washington?src=jpplatform'
        - 'best-solar-companies-idaho?src=jpplatform'
        - 'best-solar-companies-oklahoma?src=jpplatform'
        - 'best-solar-companies-tennessee?src=jpplatform'
        - 'best-solar-companies-delaware?src=jpplatform'
        - 'best-solar-companies-in-vermont?src=jpplatform'
        - 'best-solar-companies-wisconsin?src=jpplatform'
        - 'best-solar-companies-maine?src=jpplatform'
        - 'best-solar-companies-mississippi?src=jpplatform'
        - 'best-solar-companies-alabama?src=jpplatform'
        - 'best-solar-companies-alaska?src=jpplatform'
        - 'best-solar-companies-montana?src=jpplatform'
        - 'best-walk-in-tubs-with-shower?src=jpplatform'
        - 'best-solar-companies-louisiana?src=jpplatform'
        - 'best-solar-companies-in-kansas?src=jpplatform'
        - 'best-solar-companies-west-virginia?src=jpplatform'
        - 'sunrun-vs-tesla?src=jpplatform'
        - 'best-solar-companies-north-dakota?src=jpplatform'
        - 'best-solar-companies-rhode-island?src=jpplatform'
        - 'best-solar-companies-nebraska?src=jpplatform'
        - 'best-solar-companies-kentucky?src=jpplatform'
        - 'best-interstate-moving-companies?src=jpplatform'
        - 'best-solar-companies-south-dakota?src=jpplatform'
        - 'best-solar-companies-wyoming?src=jpplatform'
        - 'walk-in-tubs-for-seniors?src=jpplatform'
        - 'solar-companies-illinois?src=jpplatform'
        - 'moving-companies-connecticut?src=jpplatform'
        - 'best-solar-inverter?src=jpplatform'
        - 'commercial-solar-companies?src=jpplatform'
        - 'best-solar-companies?src=jpplatform'
        - 'solar-companies-new-jersey?src=jpplatform'
        - 'best-gutter-installation-companies?src=jpplatform'
        - 'home-warranty-texas?src=jpplatform'
        - 'home-warranty-nevada?src=jpplatform'
        - 'home-warranty-new-jersey?src=jpplatform'
        - 'home-warranty-south-carolina?src=jpplatform'
        - 'home-warranty-georgia?src=jpplatform'
        - 'home-warranty-minnesota?src=jpplatform'
        - 'home-warranty-washington?src=jpplatform'
        - 'home-warranty-maryland?src=jpplatform'
        - 'home-warranty-connecticut?src=jpplatform'
        - 'home-warranty-missouri?src=jpplatform'
        - 'home-warranty-michigan?src=jpplatform'
        - 'home-warranty-oklahoma?src=jpplatform'
        - 'home-warranty-new-york?src=jpplatform'
        - 'home-warranty-hawaii?src=jpplatform'
        - 'home-warranty-california?src=jpplatform'
        - 'home-warranty-wisconsin?src=jpplatform'
        - 'home-warranty-arizona?src=jpplatform'
        - 'home-warranty-florida?src=jpplatform'
        - 'home-warranty-virginia?src=jpplatform'
        - 'home-warranty-ohio?src=jpplatform'
        - 'home-warranty-pennsylvania?src=jpplatform'
        - 'septic-warranty?src=jpplatform'
        - 'diy-solar-panels?src=jpplatform'
        - 'home-warranty-roof?src=jpplatform'
        - 'solar-heating?src=jpplatform'
        - 'solar-companies-california?src=jpplatform'
        - 'home-warranty-iowa?src=jpplatform'
        - 'monocrystalline-vs-polycrystalline-solar-panels?src=jpplatform'
        - 'solar-hot-water-heater?src=jpplatform'
        - 'best-gutter-guards?src=jpplatform'
        - 'window-companies-0-financing?src=jpplatform'
        - 'best-gutter-guards-for-heavy-rain?src=jpplatform'
        - 'best-packing-and-moving-companies-movingherotest?src=jpplatform'
        - 'moving-companies-texas?src=jpplatform'
        - 'best-home-warranty-companies?src=jpplatform'
        - 'home-warranty-north-carolina?src=jpplatform'
        - 'best-window-brands-slhtest?src=jpplatform'
        - 'best-gutter-guards-team?src=jpplatform'
        - 'best-gutter-guards-hero?src=jpplatform'
        - '637?src=jpplatform'
        - 'seod-685-qa-test?src=jpplatform'
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
