basic:
    name: SEOD-653
    environments:
        production: 'https://thisoldhouse.jppadmin.com/'
        staging: 'https://staging.thisoldhouse.jppadmin.com/'
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - '/home-finances/best-pet-insurance?src=jpplatform'
        - '/gutters/best-gutter-guards?src=jpplatform'
        - '/pest-control/best-pest-control-companies?src=jpplatform'
        - '/gutters/best-gutter-guards-for-pine-needles?src=jpplatform'
        - '/home-finances/home-warranty-new-hampshire?src=jpplatform'
        - '/home-finances/home-warranty-vermont?src=jpplatform'
        - '/home-finances/home-warranty-wyoming?src=jpplatform'
        - '/home-finances/home-warranty-north-dakota?src=jpplatform'
        - '/home-finances/home-warranty-alaska?src=jpplatform'
        - '/home-finances/home-warranty-hawaii?src=jpplatform'
        - '/home-finances/home-warranty-montana?src=jpplatform'
        - '/home-finances/home-warranty-south-dakota?src=jpplatform'
        - '/home-finances/home-warranty-nebraska?src=jpplatform'
        - '/home-finances/home-warranty-maine?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies?src=jpplatform'
        - '/home-finances/home-warranty-mississippi?src=jpplatform'
        - '/home-finances/home-warranty-kentucky?src=jpplatform'
        - '/home-finances/home-warranty-kansas?src=jpplatform'
        - '/home-finances/home-warranty-idaho?src=jpplatform'
        - '/solar-alternative-energy/solar-companies-florida?src=jpplatform'
        - '/home-finances/home-warranty-oklahoma?src=jpplatform'
        - '/home-finances/home-warranty-west-virginia?src=jpplatform'
        - '/home-finances/home-warranty-rhode-island?src=jpplatform'
        - '/home-finances/home-warranty-alabama?src=jpplatform'
        - '/home-finances/home-warranty-iowa?src=jpplatform'
        - '/home-finances/home-warranty-connecticut?src=jpplatform'
        - '/home-finances/home-warranty-new-mexico?src=jpplatform'
        - '/solar-alternative-energy/solar-companies-california?src=jpplatform'
        - '/solar-alternative-energy/solar-companies-massachusetts?src=jpplatform'
        - '/home-finances/home-warranty-wisconsin?src=jpplatform'
        - '/home-finances/home-warranty-delaware?src=jpplatform'
        - '/solar-alternative-energy/best-solar-panels-for-homes?src=jpplatform'
        - '/solar-alternative-energy/solar-companies-new-jersey?src=jpplatform'
        - '/home-finances/home-warranty-utah?src=jpplatform'
        - '/home-finances/home-warranty-maryland?src=jpplatform'
        - '/home-finances/home-warranty-massachusetts?src=jpplatform'
        - '/home-finances/home-warranty-arkansas?src=jpplatform'
        - '/home-finances/home-warranty-new-york?src=jpplatform'
        - '/solar-alternative-energy/solar-companies-arizona?src=jpplatform'
        - '/home-finances/home-warranty-south-carolina?src=jpplatform'
        - '/home-finances/home-warranty-michigan?src=jpplatform'
        - '/home-finances/home-warranty-oregon?src=jpplatform'
        - '/home-finances/home-warranty-indiana?src=jpplatform'
        - '/home-finances/home-warranty-tennessee?src=jpplatform'
        - '/home-finances/home-warranty-illinois?src=jpplatform'
        - '/home-finances/allied-home-warranty?src=jpplatform'
        - '/home-finances/usaa-home-warranty?src=jpplatform'
        - '/home-finances/freedom-home-warranty?src=jpplatform'
        - '/home-finances/globe-home-protection?src=jpplatform'
        - '/home-finances/home-warranty-washington?src=jpplatform'
        - '/home-finances/home-warranty-colorado?src=jpplatform'
        - '/home-finances/home-warranty-georgia?src=jpplatform'
        - '/home-finances/septic-warranty?src=jpplatform'
        - '/home-finances/home-warranty-minnesota?src=jpplatform'
        - '/home-finances/home-warranty-pennsylvania?src=jpplatform'
        - '/home-finances/home-warranty-louisiana?src=jpplatform'
        - '/home-finances/home-warranty-missouri?src=jpplatform'
        - '/home-finances/home-warranty-ohio?src=jpplatform'
        - '/home-finances/365-home-warranty?src=jpplatform'
        - '/home-finances/home-warranty-nevada?src=jpplatform'
        - '/home-finances/home-warranty-new-jersey?src=jpplatform'
        - '/home-finances/home-warranty-virginia?src=jpplatform'
        - '/home-finances/home-warranty-north-carolina?src=jpplatform'
        - '/home-finances/home-warranty-florida?src=jpplatform'
        - '/home-finances/home-warranty-texas?src=jpplatform'
        - '/home-finances/home-warranty-arizona?src=jpplatform'
        - '/home-finances/home-warranty-california?src=jpplatform'
        - '/home-finances/amazon-home-warranty?src=jpplatform'
        - '/home-finances/sewer-line-warranty?src=jpplatform'
        - '/home-finances/best-home-warranty-for-high-end-appliances?src=jpplatform'
        - '/home-finances/worst-home-warranty-companies?src=jpplatform'
        - '/home-finances/pool-warranty?src=jpplatform'
        - '/home-finances/best-refrigerator-warranty?src=jpplatform'
        - '/home-finances/home-warranty-roof?src=jpplatform'
        - '/home-finances/home-warranty-plumbing?src=jpplatform'
        - '/home-finances/home-appliance-insurance?src=jpplatform'
        - '/home-finances/home-warranty-for-condo?src=jpplatform'
        - '/home-finances/mobile-home-warranty?src=jpplatform'
        - '/home-finances/best-home-warranty-for-hvac?src=jpplatform'
        - '/home-finances/home-warranty-furnace?src=jpplatform'
        - '/home-finances/home-warranty-for-veterans?src=jpplatform'
        - '/home-finances/home-warranty-for-rental-property?src=jpplatform'
        - '/home-finances/cheapest-home-warranty?src=jpplatform'
        - '/home-finances/best-home-warranty-companies?src=jpplatform'
        - '/home-finances/well-warranty?src=jpplatform'
        - '/moving/pet-shipping-companies?src=jpplatform'
        - '/moving/best-moving-companies-for-seniors?src=jpplatform'
        - '/moving/moving-companies-georgia?src=jpplatform'
        - '/moving/moving-companies-kentucky?src=jpplatform'
        - '/moving/moving-companies-nevada?src=jpplatform'
        - '/moving/best-moving-companies-for-apartments?src=jpplatform'
        - '/moving/moving-companies-minnesota?src=jpplatform'
        - '/moving/moving-from-new-york-to-california?src=jpplatform'
        - '/moving/moving-companies-washington?src=jpplatform'
        - '/moving/moving-companies-louisiana?src=jpplatform'
        - '/moving/best-long-distance-moving-companies?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-texas?src=jpplatform'
        - '/moving/moving-companies-south-carolina?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-colorado?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-north-carolina?src=jpplatform'
        - '/moving/moving-companies-utah?src=jpplatform'
        - '/moving/moving-companies-tennessee?src=jpplatform'
        - '/solar-alternative-energy/cheap-solar-panels?src=jpplatform'
        - '/moving/moving-companies-maine?src=jpplatform'
        - '/moving/best-packing-and-moving-companies?src=jpplatform'
        - '/moving/cheapest-moving-containers?src=jpplatform'
        - '/moving/best-interstate-moving-companies?src=jpplatform'
        - '/moving/moving-companies-arizona?src=jpplatform'
        - '/moving/moving-companies-for-small-moves?src=jpplatform'
        - '/moving/moving-companies-illinois?src=jpplatform'
        - '/moving/cheap-moving-companies?src=jpplatform'
        - '/moving/moving-companies-california?src=jpplatform'
        - '/moving/moving-companies-florida?src=jpplatform'
        - '/moving/best-moving-companies?src=jpplatform'
        - '/moving/moving-companies-new-jersey?src=jpplatform'
        - '/moving/moving-companies-virginia?src=jpplatform'
        - '/moving/cheapest-moving-truck-rental?src=jpplatform'
        - '/moving/moving-companies-alabama?src=jpplatform'
        - '/moving/moving-companies-rhode-island?src=jpplatform'
        - '/moving/moving-companies-oregon?src=jpplatform'
        - '/moving/best-moving-container-companies?src=jpplatform'
        - '/moving/moving-companies-wisconsin?src=jpplatform'
        - '/moving/moving-companies-delaware?src=jpplatform'
        - '/moving/moving-companies-hawaii?src=jpplatform'
        - '/moving/moving-companies-texas?src=jpplatform'
        - '/moving/best-moving-companies-for-antiques?src=jpplatform'
        - '/moving/moving-companies-for-military-members?src=jpplatform'
        - '/moving/moving-companies-connecticut?src=jpplatform'
        - '/moving/moving-companies-indiana?src=jpplatform'
        - '/moving/moving-companies-michigan?src=jpplatform'
        - '/moving/moving-companies-pennsylvania?src=jpplatform'
        - '/moving/moving-companies-maryland?src=jpplatform'
        - '/moving/moving-companies-massachusetts?src=jpplatform'
        - '/moving/moving-companies-ohio?src=jpplatform'
        - '/moving/moving-companies-north-carolina?src=jpplatform'
        - '/moving/moving-companies-colorado?src=jpplatform'
        - '/moving/moving-from-california-to-florida?src=jpplatform'
        - '/lawns/best-lawn-care-services?src=jpplatform'
        - '/moving/moving-companies-new-york?src=jpplatform'
        - '/solar-alternative-energy/solar-panel-cost-florida?src=jpplatform'
        - '/solar-alternative-energy/most-efficient-solar-panels?src=jpplatform'
        - '/solar-alternative-energy/solar-companies-new-york?src=jpplatform'
        - '/solar-alternative-energy/best-solar-batteries?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-new-mexico?src=jpplatform'
        - '/solar-alternative-energy/solar-panel-cost-new-jersey?src=jpplatform'
        - '/windows/best-replacement-windows?src=jpplatform'
        - '/solar-alternative-energy/solar-companies-pennsylvania?src=jpplatform'
        - '/windows/best-window-brands?src=jpplatform'
        - '/windows/cheap-window-replacement?src=jpplatform'
        - '/moving/best-office-moving-companies?src=jpplatform'
        - '/moving/moving-companies-arkansas?src=jpplatform'
        - '/moving/moving-companies-iowa?src=jpplatform'
        - '/moving/best-piano-movers?src=jpplatform'
        - '/solar-alternative-energy/solar-companies-south-carolina?src=jpplatform'
        - '/moving/moving-companies-mississippi?src=jpplatform'
        - '/moving/best-flat-fee-movers?src=jpplatform'
        - '/moving/moving-companies-vermont?src=jpplatform'
        - '/moving/moving-companies-south-dakota?src=jpplatform'
        - '/moving/moving-companies-alaska?src=jpplatform'
        - '/moving/moving-companies-new-hampshire?src=jpplatform'
        - '/moving/moving-companies-montana?src=jpplatform'
        - '/moving/moving-companies-kansas?src=jpplatform'
        - '/solar-alternative-energy/solar-companies-georgia?src=jpplatform'
        - '/moving/moving-companies-nebraska?src=jpplatform'
        - '/moving/moving-companies-north-dakota?src=jpplatform'
        - '/moving/moving-companies-new-mexico?src=jpplatform'
        - '/windows/best-window-installation-companies?src=jpplatform'
        - '/windows/best-storm-windows?src=jpplatform'
        - '/moving/moving-companies-idaho?src=jpplatform'
        - '/solar-alternative-energy/solar-companies-illinois?src=jpplatform'
        - '/moving/best-international-moving-companies?src=jpplatform'
        - '/moving/moving-companies-west-virginia?src=jpplatform'
        - '/moving/short-distance-moving-companies?src=jpplatform'
        - '/moving/moving-companies-oklahoma?src=jpplatform'
        - '/solar-alternative-energy/solar-companies-maryland?src=jpplatform'
        - '/solar-alternative-energy/monocrystalline-vs-polycrystalline-solar-panels?src=jpplatform'
        - '/windows/arched-window-replacement?src=jpplatform'
        - '/moving/moving-companies-missouri?src=jpplatform'
        - '/heating-cooling/best-air-conditioner-brands?src=jpplatform'
        - '/solar-alternative-energy/solar-panel-cost-arizona?src=jpplatform'
        - '/moving/moving-companies-wyoming?src=jpplatform'
        - '/home-finances/pet-wellness-plans?src=jpplatform'
        - '/solar-alternative-energy/solar-companies-utah?src=jpplatform'
        - '/moving/best-last-minute-movers?src=jpplatform'
        - '/solar-alternative-energy/best-flexible-solar-panels?src=jpplatform'
        - '/gutters/best-gutter-guards-for-metal-roofs?src=jpplatform'
        - '/solar-alternative-energy/solar-companies-connecticut?src=jpplatform'
        - '/solar-alternative-energy/diy-solar-panels?src=jpplatform'
        - '/heating-cooling/trane-ac-unit?src=jpplatform'
        - '/flooring/best-laminate-flooring?src=jpplatform'
        - '/bathrooms/best-walk-in-tubs?src=jpplatform'
        - '/heating-cooling/best-furnace-brands?src=jpplatform'
        - '/heating-cooling/wall-mounted-air-conditioner?src=jpplatform'
        - '/moving/best-luxury-moving-companies?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-virginia?src=jpplatform'
        - '/windows/best-vinyl-windows?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companes-minnesota?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-hawaii?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-nevada?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-oregon?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-ohio?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-arkansas?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-oklahoma?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-new-hampshire?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-iowa?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-tennessee?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-missouri?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-washington?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-delaware?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-idaho?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-in-vermont?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-maine?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-wisconsin?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-mississippi?src=jpplatform'
        - '/bathrooms/best-walk-in-tubs-with-shower?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-alaska?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-alabama?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-montana?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-west-virginia?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-in-kansas?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-louisiana?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-north-dakota?src=jpplatform'
        - '/solar-alternative-energy/sunrun-vs-tesla?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-nebraska?src=jpplatform'
        - '/solar-alternative-energy/solar-hot-water-heater?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-rhode-island?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-kentucky?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-south-dakota?src=jpplatform'
        - '/solar-alternative-energy/best-solar-companies-wyoming?src=jpplatform'
        - '/bathrooms/walk-in-tubs-for-seniors?src=jpplatform'
        - '/solar-alternative-energy/best-solar-inverter?src=jpplatform'
        - '/solar-alternative-energy/commercial-solar-companies?src=jpplatform'
        - '/solar-alternative-energy/solar-heating?src=jpplatform'
        - '/gutters/best-gutter-installation-companies?src=jpplatform'
        - '/windows/window-companies-0-financing?src=jpplatform'
        - '/gutters/best-gutter-guards-for-heavy-rain?src=jpplatform'
        - '/moving/best-packing-and-moving-companies-movingherotest?src=jpplatform'
        - '/uncategorized/?src=jpplatform'
        - '/home-finances/worst-home-warranty-companies-2?src=jpplatform'
        - '/home-finances/home-warranty-new-jersey-2?src=jpplatform'
        - '/solar-alternative-energy/solar-companies-illinois-2?src=jpplatform'
        - '/windows/best-window-brands-slhtest?src=jpplatform'
        - '/gutters/best-gutter-guards-hero?src=jpplatform'
        - '/gutters/best-gutter-guards-team?src=jpplatform'
        - '/uncategorized/637?src=jpplatform'
        - '/uncategorized/seod-685-qa-test?src=jpplatform'
    monitoring:
        days: {  }
        type: ''
        schedule_time: '12:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: ''
    isolate: ''
    delay: 15
    scroll: true
    headers:
        - { header: '', value: '' }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content:
        - { selector: '', type: title }
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
